export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

// export const SET_CURRENCIES = 'SET_CURRENCIES';
export const DELETE_CURRENCY_PAIR = 'DELETE_CURRENCY_PAIR';
export const ADD_CURRENCY_PAIR = 'ADD_CURRENCY_PAIR';
export const GET_CURRENCIES = 'GET_CURRENCIES';
